#!/usr/bin/env bash
set -euo pipefail

# ——— Functions definition —————————————————————————————————————————————————————

function discord::download() {
    local -r toFile="$1"

    local -r debURL='https://discord.com/api/download?platform=linux&format=deb'
    local -i exitCode=0
    local    output

    output="$( mktemp )"

    output::listItemPending 'downloading deb file' "$LIST_ITEM_INDENT"
    log::addMessage 'downloading deb file'

    scrollingRegion::create --full-window 5

    exitCode=0
    download::get "$debURL" "$toFile" |& tee "$output" || exitCode=$?

    scrollingRegion::restore
    output::cleanPreviousLines 1

    if [[ $exitCode -ne 0 ]]
    then
        output::listItemError 'failed to download deb file' "$LIST_ITEM_INDENT"
        log::addMessage 'failed to download deb file'

        output::showErrorOutputFromFile "$output" >&2
        log::addFile "$output"
    else
        output::listItemSuccess 'deb file downloaded' "$LIST_ITEM_INDENT"
        log::addMessage 'deb file downloaded'
    fi

    rm "$output"

    return $exitCode
}
declare -rf discord::download

function discord::installPackage() {
    local -r debFile="$1"

    local    output
    local -i exitCode=0

    output::listItemPending 'installing package' "$LIST_ITEM_INDENT"
    log::addMessage 'installing deb package'

    output="$( mktemp )"
    scrollingRegion::create --full-window --header-min-height 1 5
    packageManager::install 'install discord.' "$debFile" |& tee "$output" || exitCode=$?
    scrollingRegion::restore

    output::cleanPreviousLines 1
    if [[ $exitCode -ne 0 ]]
    then
        output::listItemError 'failed to install discord.deb package' "$LIST_ITEM_INDENT"
        log::addMessage 'failed to install discord.deb package'

        output::showErrorOutputFromFile "$output" >&2
        log::addFile "$output"
    else
        output::listItemSuccess 'package installed' "$LIST_ITEM_INDENT"
        log::addMessage 'package installed'
    fi

    log::addMessage 'removing deb file'
    rm "$debFile" "$output"
    log::addMessage 'deb file removed'

    return $exitCode
}
declare -rf discord::installPackage

function discord::main() {
    local -r debFile=./discord.deb

    log::addMessage 'start discord install'

    softwareParseOpt "$@" || return $?
    discord::download "$debFile" || return $?
    discord::installPackage "$debFile" || return $?
}
declare -rf discord::main

# ——— Script execution —————————————————————————————————————————————————————————

declare PROJECT_ROOT
PROJECT_ROOT="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
readonly PROJECT_ROOT

source "$PROJECT_ROOT/lib/download.lib.sh"
source "$PROJECT_ROOT/lib/log.lib.sh"
source "$PROJECT_ROOT/lib/output.lib.sh"
source "$PROJECT_ROOT/lib/package-manager.lib.sh"
source "$PROJECT_ROOT/lib/scrolling-region.lib.sh"
source "$PROJECT_ROOT/lib/software-parse-opt.lib.sh"

discord::main "$@"
