#!/usr/bin/env bash
set -euo pipefail

# ——— Functions definition —————————————————————————————————————————————————————

function sublimeText::main() {
    local    output
    local -i exitCode

    log::addMessage 'install sublime-text'

    output::pending 'installing package'
    log::addMessage 'installing package'

    scrollingRegion::create --full-window 5

    exitCode=0
    output="$( mktemp )"

    packageManager::installRepository \
        --suites 'apt/stable/' \
        --components '' \
        --key-url https://download.sublimetext.com/sublimehq-pub.gpg \
        sublime-text \
        https://download.sublimetext.com/ \
        |& tee "$output" && \
    packageManager::install \
        'install sublime-text' sublime-text |& tee -a "$output" || exitCode=$?

    scrollingRegion::restore
    output::cleanPreviousLines 1

    if [[ $exitCode -ne 0 ]]
    then
        output::error 'failed to install sublime-text'
        log::addMessage 'failed to install sublime-text'

        output::showErrorOutputFromFile "$output" >&2
        log::addFile "$output"
    else
        output::success 'sublime-text installation completed'
        log::addMessage 'sublime-text installation completed'
    fi

    rm "$output"

    return $exitCode
}
declare -rf sublimeText::main

# ——— Script execution —————————————————————————————————————————————————————————

declare PROJECT_ROOT
PROJECT_ROOT="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
readonly PROJECT_ROOT

source "$PROJECT_ROOT/lib/log.lib.sh"
source "$PROJECT_ROOT/lib/output.lib.sh"
source "$PROJECT_ROOT/lib/package-manager.lib.sh"
source "$PROJECT_ROOT/lib/scrolling-region.lib.sh"

sublimeText::main
