#!/usr/bin/env bash
set -euo pipefail

declare PROJECT_ROOT
PROJECT_ROOT="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
readonly PROJECT_ROOT

source "$PROJECT_ROOT/lib/software-simple-install.lib.sh"

installSimplePackage vlc
